[package]
name = "maelbreaker"
authors = ["Rafael Bayer"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/rafibayer/maelbreaker/"

[dependencies]
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
